### ISSUE TITLE
Raspberry Pi k0s worker ingress-nginx - port 80 is already in use. Please check the flag --http-port

### ISSUE THREAD

**Issue by ksawerykarwacki** [k0sproject/k0s#1231]
**Version**
```
v1.22.2+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
**What happened?**
Ingress-nginx is not able to run container due with complain that:

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.0.4
  Build:         9b78b6c197b48116243922170875af4aa752ee59
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.9

-------------------------------------------------------------------------------

F1027 21:20:06.448907       8 main.go:67] port 80 is already in use. Please check the flag --http-port
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        k8s.io/klog/v2@v2.10.0/klog.go:1026 +0xac
k8s.io/klog/v2.(*loggingT).output(0x2420420, 0x3, {0x0, 0x0}, 0x40000a0cb0, 0x1, {0x1b22ba4, 0x7}, 0x43, 0x0)
        k8s.io/klog/v2@v2.10.0/klog.go:975 +0x640
k8s.io/klog/v2.(*loggingT).printDepth(0x2420420, 0x3, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x40000a21c0, 0x1, 0x1})
        k8s.io/klog/v2@v2.10.0/klog.go:735 +0x1b4
k8s.io/klog/v2.(*loggingT).print(...)
        k8s.io/klog/v2@v2.10.0/klog.go:717
k8s.io/klog/v2.Fatal(...)
        k8s.io/klog/v2@v2.10.0/klog.go:1494
main.main()
        k8s.io/ingress-nginx/cmd/nginx/main.go:67 +0x1fc

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2420420)
        k8s.io/klog/v2@v2.10.0/klog.go:1169 +0x70
created by k8s.io/klog/v2.init.0
        k8s.io/klog/v2@v2.10.0/klog.go:420 +0x14c
```

Folks at ingress-nginx are sure that my ports are in use but I run `sudo netstat -tunlp` and those are the results:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:50051         0.0.0.0:*               LISTEN      1343/kube-router
tcp        0      0 192.168.5.39:50051      0.0.0.0:*               LISTEN      1343/kube-router
tcp        0      0 0.0.0.0:31653           0.0.0.0:*               LISTEN      8056/kube-proxy
tcp        0      0 0.0.0.0:31878           0.0.0.0:*               LISTEN      8056/kube-proxy
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      693/kubelet
tcp        0      0 127.0.0.1:36237         0.0.0.0:*               LISTEN      687/containerd
tcp        0      0 192.168.5.39:7472       0.0.0.0:*               LISTEN      1722/cmd
tcp        0      0 192.168.5.39:179        0.0.0.0:*               LISTEN      1343/kube-router
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      582/sshd
tcp        0      0 0.0.0.0:43161           0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.5.39:7934       0.0.0.0:*               LISTEN      1722/cmd
tcp6       0      0 :::10249                :::*                    LISTEN      8056/kube-proxy
tcp6       0      0 :::10250                :::*                    LISTEN      693/kubelet
tcp6       0      0 :::9100                 :::*                    LISTEN      31880/node_exporter
tcp6       0      0 :::10256                :::*                    LISTEN      8056/kube-proxy
tcp6       0      0 :::8080                 :::*                    LISTEN      1343/kube-router
tcp6       0      0 ::1:179                 :::*                    LISTEN      1343/kube-router
tcp6       0      0 :::20244                :::*                    LISTEN      1343/kube-router
tcp6       0      0 :::22                   :::*                    LISTEN      582/sshd
udp        0      0 192.168.5.39:7934       0.0.0.0:*                           1722/cmd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           576/dhcpcd
udp        0      0 0.0.0.0:32950           0.0.0.0:*                           253/avahi-daemon: r
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           253/avahi-daemon: r
udp6       0      0 :::37456                :::*                                253/avahi-daemon: r
udp6       0      0 :::5353                 :::*                                253/avahi-daemon: r
```

Everything works fine on my ubuntu vm  which is both controller and worker. One thing specific about Raspberry nodes is that they run Raspbian x64 and use PXE Boot with NFS mounts so no physical disk/sd is attached (I had to change snapshotter to native to make k0s work).

I also checked and no service or pod uses port 80 on those nodes. Is there a way something internal for k0s reserved it? Is there a way to figure this out?

**Comment by mviitane** [comment]
I haven't seen problems when following this example on k0s even though there was a web server pod listening on port 80.
https://docs.k0sproject.io/main/examples/nginx-ingress/

I'd re-check the Raspberry host for open ports, but this doesn't seem k0s related.
