### ISSUE TITLE
TestBasicReconcilerWithNoExistingEndpoint depends on internet

### ISSUE THREAD

**Issue by juanluisvaladas** [k0sproject/k0s#2895]
### What happened?

TestBasicReconcilerWithNoExistingEndpoint will fail if:
1- There is no internet connection
2- The DNS resolution includes ipv6 addresses.

### Steps to reproduce

1. disconnect from the internet
2. make check-unit

### Expected behavior

Unit tests don't depend on external services

### Actual behavior

Unit tests depend on the internet

### Screenshots and logs

No internet:

```
--- FAIL: TestBasicReconcilerWithNoExistingEndpoint (0.01s)
    apiendpointreconciler_test.go:83:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:83
        	Error:      	Received unexpected error:
        	            	while resolving external address "get.k0s.sh": lookup get.k0s.sh on 192.168.65.7:53: no such host
        	Test:       	TestBasicReconcilerWithNoExistingEndpoint
    apiendpointreconciler_test.go:211:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:211
        	            				/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:84
        	Error:      	Received unexpected error:
        	            	endpoints "kubernetes" not found
        	Test:       	TestBasicReconcilerWithNoExistingEndpoint
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e1cd64]

goroutine 108 [running]:
testing.tRunner.func1.2({0x31c2a00, 0x5221e70})
	/usr/local/go/src/testing/testing.go:1526 +0x278
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x448
panic({0x31c2a00, 0x5221e70})
	/usr/local/go/src/runtime/panic.go:890 +0x248
github.com/k0sproject/k0s/pkg/component/controller.verifyEndpointAddresses(0x3b8e580?, {0x52379c0, 0x4, 0x4}, {{0x3be0f00, 0xc000897a20}, {0x3b8d000, 0xc000897ad0}, {0x3bc78e8, 0xc0009f4d20}, ...})
	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:212 +0x144
github.com/k0sproject/k0s/pkg/component/controller.TestBasicReconcilerWithNoExistingEndpoint(0x0?)
	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:84 +0x28c
testing.tRunner(0xc000583d40, 0x370f5c0)
	/usr/local/go/src/testing/testing.go:1576 +0x184
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x5b8
FAIL	github.com/k0sproject/k0s/pkg/component/controller	0.231s
```

Internet with ipv6 resolution:

```
--- FAIL: TestBasicReconcilerWithNoExistingEndpoint (0.24s)
    apiendpointreconciler_test.go:212:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:212
        	            				/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:84
        	Error:      	Not equal:
        	            	expected: []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153"}
        	            	actual  : []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153", "64:ff9b::b9c7:6c99", "64:ff9b::b9c7:6d99", "64:ff9b::b9c7:6e99", "64:ff9b::b9c7:6f99"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-([]string) (len=4) {
        	            	+([]string) (len=8) {
        	            	  (string) (len=15) "185.199.108.153",
        	            	@@ -4,3 +4,7 @@
        	            	  (string) (len=15) "185.199.110.153",
        	            	- (string) (len=15) "185.199.111.153"
        	            	+ (string) (len=15) "185.199.111.153",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6c99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6d99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6e99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6f99"
        	            	 }
        	Test:       	TestBasicReconcilerWithNoExistingEndpoint
--- FAIL: TestBasicReconcilerWithEmptyEndpointSubset (0.00s)
    apiendpointreconciler_test.go:212:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:212
        	            				/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:119
        	Error:      	Not equal:
        	            	expected: []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153"}
        	            	actual  : []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153", "64:ff9b::b9c7:6c99", "64:ff9b::b9c7:6d99", "64:ff9b::b9c7:6e99", "64:ff9b::b9c7:6f99"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-([]string) (len=4) {
        	            	+([]string) (len=8) {
        	            	  (string) (len=15) "185.199.108.153",
        	            	@@ -4,3 +4,7 @@
        	            	  (string) (len=15) "185.199.110.153",
        	            	- (string) (len=15) "185.199.111.153"
        	            	+ (string) (len=15) "185.199.111.153",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6c99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6d99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6e99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6f99"
        	            	 }
        	Test:       	TestBasicReconcilerWithEmptyEndpointSubset
--- FAIL: TestReconcilerWithNoNeedForUpdate (0.00s)
    apiendpointreconciler_test.go:212:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:212
        	            				/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:161
        	Error:      	Not equal:
        	            	expected: []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153"}
        	            	actual  : []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153", "64:ff9b::b9c7:6c99", "64:ff9b::b9c7:6d99", "64:ff9b::b9c7:6e99", "64:ff9b::b9c7:6f99"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-([]string) (len=4) {
        	            	+([]string) (len=8) {
        	            	  (string) (len=15) "185.199.108.153",
        	            	@@ -4,3 +4,7 @@
        	            	  (string) (len=15) "185.199.110.153",
        	            	- (string) (len=15) "185.199.111.153"
        	            	+ (string) (len=15) "185.199.111.153",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6c99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6d99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6e99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6f99"
        	            	 }
        	Test:       	TestReconcilerWithNoNeedForUpdate
--- FAIL: TestReconcilerWithNeedForUpdate (0.01s)
    apiendpointreconciler_test.go:212:
        	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:212
        	            				/go/src/github.com/k0sproject/k0s/pkg/component/controller/apiendpointreconciler_test.go:204
        	Error:      	Not equal:
        	            	expected: []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153"}
        	            	actual  : []string{"185.199.108.153", "185.199.109.153", "185.199.110.153", "185.199.111.153", "64:ff9b::b9c7:6c99", "64:ff9b::b9c7:6d99", "64:ff9b::b9c7:6e99", "64:ff9b::b9c7:6f99"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-([]string) (len=4) {
        	            	+([]string) (len=8) {
        	            	  (string) (len=15) "185.199.108.153",
        	            	@@ -4,3 +4,7 @@
        	            	  (string) (len=15) "185.199.110.153",
        	            	- (string) (len=15) "185.199.111.153"
        	            	+ (string) (len=15) "185.199.111.153",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6c99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6d99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6e99",
        	            	+ (string) (len=18) "64:ff9b::b9c7:6f99"
        	            	 }
        	Test:       	TestReconcilerWithNeedForUpdate
```

**Comment by juanluisvaladas** [comment]
I'm going to attempt to fix this using a [go-mockdns server](https://github.com/foxcpp/go-mockdns/blob/v1.0.0/example_test.go#L28-L46) as I believe the only issue is in the resolver.
