### ISSUE TITLE
Panic: concurrent map read and map write

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#4532]
Observed while running [integration tests](https://github.com/k0sproject/k0s/actions/runs/9347350020/job/25724172138) on arm64. This happened on a PR build, but I reckon the problem this is independent from the changes in that PR.

If I interpret the below stack trace correctly, this happens when using the Kubernetes [`runtime.Scheme`](https://pkg.go.dev/k8s.io/apimachinery@v0.30.1/pkg/runtime#Scheme) object at address `0x4000343ea0` concurrently.

Read happens in goroutine 3459 at [scheme.go:474](https://github.com/kubernetes/kubernetes/blob/v1.30.1/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L474), the k0s entrypoint is at [lease_pool.go:208](https://github.com/k0sproject/k0s/blob/v1.30.1%2Bk0s.0/pkg/leaderelection/lease_pool.go#L208).

<details>
<summary>goroutine 3459 [running]:</summary>

```text
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0x4000343ea0, 0x1, {0x3e0ef10, 0x4000813380}, {0x3e0e8f8, 0x4001ce7e40})
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme.go:474 +0x23c
k8s.io/apimachinery/pkg/runtime.(*Scheme).ConvertToVersion(0x34406e0?, {0x3e0ef10?, 0x4000813380?}, {0x3e0e8f8?, 0x4001ce7e40?})
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme.go:438 +0x40
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0x5cb9200, {0x3e0ef10, 0x4000813380}, {{0x36bfe27, 0x13}, {0x366bc4c, 0x2}})
	k8s.io/apimachinery@v0.30.1/pkg/runtime/codec.go:196 +0x120
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0x4001b2ec60, {0x3e0ef10?, 0x4000813380?}, {0x3e0f1b8?, 0x5cb9200?}, {{0x36bfe27?, 0x140?}, {0x366bc4c?, 0x40023e98b8?}})
	k8s.io/client-go@v0.30.1/rest/request.go:377 +0x5c
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	k8s.io/client-go@v0.30.1/rest/request.go:370
k8s.io/client-go/kubernetes/typed/coordination/v1.(*leases).Create(0x4001ce7e20, {0x3e39108, 0x4002048fa0}, 0x4001feab40, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, ...}, ...})
	k8s.io/client-go@v0.30.1/kubernetes/typed/coordination/v1/lease.go:121 +0x13c
k8s.io/client-go/tools/leaderelection/resourcelock.(*LeaseLock).Create(0x4001c1d440, {0x3e39108, 0x4002048fa0}, {{0x4000ea8a20, 0x20}, 0x3c, {{0xc18f8091a47209e9, 0x2aca91cc8, 0x5e8b0c0}}, {{0xc18f8091a47209e9, ...}}, ...})
	k8s.io/client-go@v0.30.1/tools/leaderelection/resourcelock/leaselock.go:58 +0x28c
k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew(0x4001c1d560, {0x3e39108, 0x4002048fa0})
	k8s.io/client-go@v0.30.1/tools/leaderelection/leaderelection.go:350 +0x5c8
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1()
	k8s.io/client-go@v0.30.1/tools/leaderelection/leaderelection.go:252 +0x50
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x40023e9ee0, {0x3dfece0, 0x4001b23710}, 0x1, 0x4001f748a0)
	k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40023e9ee0, 0x12a05f200, 0x3ff3333333333333, 0x1, 0x4001f748a0)
	k8s.io/apimachinery@v0.30.1/pkg/util/wait/backoff.go:204 +0x80
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire(0x4001c1d560, {0x3e39108?, 0x4001eca780?})
	k8s.io/client-go@v0.30.1/tools/leaderelection/leaderelection.go:251 +0x188
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x4001c1d560, {0x3e39108, 0x4001eca780})
	k8s.io/client-go@v0.30.1/tools/leaderelection/leaderelection.go:208 +0x5c
github.com/k0sproject/k0s/pkg/leaderelection.(*LeasePool).Watch.func3()
	github.com/k0sproject/k0s/pkg/leaderelection/lease_pool.go:208 +0x44
created by github.com/k0sproject/k0s/pkg/leaderelection.(*LeasePool).Watch in goroutine 3458
	github.com/k0sproject/k0s/pkg/leaderelection/lease_pool.go:206 +0x398
```
</details>

Write happensin goroutine 3461, presumably in [scheme.go:181](https://github.com/kubernetes/kubernetes/blob/v1.30.1/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L181), the k0s entrypoint is [root_controller.go:166](https://github.com/k0sproject/k0s/blob/v1.30.1+k0s.0/pkg/autopilot/controller/root_controller.go#L166).

<details>
<summary>goroutine 3461 [runnable]:</summary>

```text
reflect.Value.Field({0x40005bca20?, 0x4001ecbc20?, 0x199?}, 0x1?)
	reflect/value.go:1282 +0x108
reflect.FuncOf({0x4000ff79c0, 0x2, 0x8?}, {0x5f077c0, 0x0, 0x1?}, 0x0)
	reflect/type.go:1776 +0x100
reflect.(*rtype).Method(0x356e620, 0x1)
	reflect/type.go:615 +0x3ec
reflect.(*rtype).MethodByName(0x356e620, {0x3698259, 0xc})
	reflect/type.go:651 +0x280
reflect.Value.MethodByName({0x356e620?, 0x5e8ba60?, 0x4001d72918?}, {0x3698259?, 0x0?})
	reflect/value.go:2117 +0x48
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0x4000343ea0, {{0x36b2801, 0x11}, {0x367ecd0, 0x7}, {0x2ccb351, 0xb}}, {0x3e0ee98, 0x5e8ba60})
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme.go:184 +0x408
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0x4000343ea0, {{0x36b2801?, 0x11?}, {0x367ecd0?, 0xa?}}, {0x5cc0f40?, 0x6?, 0x3e0efb0?})
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme.go:148 +0x124
k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0x4000343ea0, {{0x36b2801?, 0x4001966c88?}, {0x367ecd0?, 0x4000a710e0?}})
	k8s.io/apimachinery@v0.30.1/pkg/apis/meta/v1/register.go:73 +0x158
github.com/k0sproject/k0s/pkg/apis/k0s/v1beta1.init.0.(*Builder).Register.func1(0x4000343ea0)
	sigs.k8s.io/controller-runtime@v0.18.3/pkg/scheme/scheme.go:72 +0x60
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme_builder.go:29
sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme(0x0?, 0x4000343ea0)
	sigs.k8s.io/controller-runtime@v0.18.3/pkg/scheme/scheme.go:86 +0x64
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
	k8s.io/apimachinery@v0.30.1/pkg/runtime/scheme_builder.go:29
github.com/k0sproject/k0s/pkg/autopilot/controller.(*rootController).startSubControllerRoutine(0x4001a271e0, {0x3e39108, 0x4001eca870}, 0x40004e8b60, {0x367f726, 0x7})
	github.com/k0sproject/k0s/pkg/autopilot/controller/root_controller.go:166 +0x2b0
github.com/k0sproject/k0s/pkg/autopilot/controller.(*rootController).startSubControllers.func1()
	github.com/k0sproject/k0s/pkg/autopilot/controller/root_controller.go:248 +0xa0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2887
	golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98
```
</details>

The full stack trace may be found in the integration test's diagnostic files: [smoketest-arm64-check-basic-files.zip](https://github.com/user-attachments/files/15532438/smoketest-arm64-check-basic-files.zip)

**Comment by twz123** [comment]
The docs about runtime.Scheme say: "Schemes are not expected to change at runtime and are only threadsafe after registration is complete.". So I suppose something is not honoring this during k0s startup.
